### Получение объектов из БД по заданным параметрам вида: тип адреса: название адреса
POST http://localhost:8080/api/addr/obj/dateAndTypeName?date=2010-12-20&typeName=1455887

### Сохранение объекта в БД
POST http://localhost:8080/api/addr/obj

### Получение объекта из БД по id
POST http://localhost:8080/api/addr/obj/1


### Получение всех объектов из БД по date
GET http://localhost:8080/api/addr/obj/2023-10-31


